### PR TITLE
Update tea.yaml

### PR DESCRIPTION
**Pull request by ajeek**
Updated Tea Address

### CODE REVIEW

**Comment by michaelessiet** [comment]
This is spam. Please review this for more context https://github.com/TryGhost/Ghost/pull/19743

**Comment by michaelessiet** [comment]
That is not allowed and against the rules. These are not your projects and you are wasting developer's time and effort by spamming these PRs every where.

**Comment by ajeek** [comment]
I saw in the tea forum that, its is allowed but nevertheless, Sorry for that. I will take heed your  delete your fork immediately.

**Comment by michaelessiet** [comment]
Yes, please close your PRs and delete the forks

**Comment by michaelessiet** [comment]
Your other Pull requests are still open. You have 11 hours to close them or else you will be banned from using tea

**Pull request closed without merging**
